sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD) # gets current GIT SHA value for new deployments
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1 # configures google cloud SDK without needing interaction on prompts (no ability to interact with prompts so needed)
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null; # downloads google cloud SDK and installs locally on instance assigned by TravisCI
  - source $HOME/google-cloud-sdk/path.bash.inc # configuration to modify shell thru source command
  - gcloud components update kubectl # installs and updates kubectl inside travis environment (used for configuration and imperative commands)
  - gcloud auth activate-service-account --key-file service-account.json # equivalent to AWS IAM, tells google SDK who we are and provide credentials from service-account.json file
  - gcloud config set project multi-k8s-355820 # check/configure true project name
  - gcloud config set compute/zone us-east1-d # check/configure location
  - gcloud container clusters get-credentials multi-cluster # name of kubernetes cluster, configure to work specifically with this cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin # login to docker using environment variables in Travis dashboard
  - docker build -t danedabomb/react-test -f ./client/Dockerfile.dev ./client # dockerfile then build context

script:
  - docker run -e CI=true danedabomb/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master # only run the above command if new push to master branch
